name: marcaii_flutter
description: Horas Extras

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.0
  sqflite: any
  path_provider: any
  scoped_model: "^0.2.0"
  numberpicker: "^0.1.4"
  flutter_masked_text: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  intl_translation: "^0.16.7"

flutter:
  uses-material-design: true

analyzer:
  strong-mode:
    implicit-casts: false