name: marcaii_flutter
description: Horas Extras

dependencies:
  flutter:
    sdk: flutter  

  flutter_localizations:
    sdk: flutter
  sqflite: ^0.11.2+2
  path_provider: ^0.4.1
  scoped_model: ^0.3.0
  numberpicker: ^0.1.6
  flutter_masked_text: ^0.6.0
  shared_preferences: ^0.4.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  intl_translation: "^0.17.0"

flutter:
  uses-material-design: true
  assets:
    - assets/

analyzer:
  strong-mode:
    implicit-casts: false